# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://bhumikao.github.io/
title: Bhumika Ojha
author: Bhumika Ojha
description: Personal blog and resume
avatar: profile.png
email: bhumikao@iitk.ac.in
github: bhumikao # username
# twitter: username
# linkedin: username
facebook: bhumika.ojha.14

# needed for travis-ci build
exclude: [vendor]
